### ISSUE TITLE
Is it possible to use message pack instead of json/xml for request bodies?

### ISSUE THREAD

**Issue by vamshiaruru** [ggicci/httpin#100]
Hi, thanks for the great library!

Right now, the library supports `json`, `xml` for request bodies. Is it possible to support for msgpack as well? Can I write a custom directive executor for this new format? 

Should I be using `RegisterBodyFormat`, `RegisterBodyDecoder` or something else?

Any guidance is appreicated. TIA!

**Comment by ggicci** [comment]
Please check out https://pkg.go.dev/github.com/ggicci/httpin@v0.17.0/core#RegisterBodyFormat

**Comment by vamshiaruru** [comment]
Thanks, just wanted to confirm!
