### ISSUE TITLE
How to know which field is wrong if error?

### ISSUE THREAD

**Issue by Crandel** [ggicci/httpin#112]
Without exposing `InvalidFieldError` from core package how to know which query param is wrong, if I need to have custom error message for end user? Even with `CustomErrorHandler` it still not possible to separate which query param is wrong in case I need to parse many params in the same time and provide simple error message to the end user

For example:
```
invalid response
got:
   {StatusCode:400 Error:failed to parse request queries: invalid field "ProfileIntegrationID": resolve field "ProfileIntegrationID (string)" failed: execute directive "required" with args [] failed: missing required field}
want:
   {StatusCode:400 Error:failed to parse request queries: could not parse ProfileIntegrationID parameter}
```

End user should not know anything about some "strange" directives, etc.
The only option right now is to parse error message as string.

**Comment by ggicci** [comment]
hi @Crandel , We can do a *type assertion* like this:

```go
var invalidFieldError *core.InvalidFieldError
if errors.As(err, &invalidFieldError) {
    // ..., now you can access invalidFieldError here
}
```

Please let me know if this is what you want. Also here's an example: https://github.com/ggicci/httpin/blob/main/httpin_test.go#L166-L175

**Comment by Crandel** [comment]
Hi @ggicci thank you for this proposal. This would be the best solution

**Comment by Crandel** [comment]
Hi ggicci, 
please reopen this issue as it is not done yet. I can't use `var invalidFieldError *core.InvalidFieldError` as it is not exported. Please make it public.
