### ISSUE TITLE
implement a "default" directive

### ISSUE THREAD

**Issue by ggicci** [ggicci/httpin#26]
Refer to https://github.com/gorilla/schema/issues/182 https://github.com/gorilla/schema/issues/153

```go
type Pagination struct {
	Page     int64 `in:"query=page;default=1"`
	PageSize int64 `in:"query=page_size;default=20"`
}
```

**Comment by ggicci** [comment]
Vote: do we need this?

**Comment by gamelaster** [comment]
I was just about to create issue about this, this feature would be amazing to have 😊

**Comment by ggicci** [comment]
@gamelaster Thanks for your suggestion and I will take this into account :)

**Comment by ggicci** [comment]
Closed since a very basic implementation has been merged and released.

See release [v0.8.0](https://github.com/ggicci/httpin/releases/tag/v0.8.0) and the corresponding documentation at https://ggicci.github.io/httpin/directives/default.
