### ISSUE TITLE
implement some frequently used directives as builtins

### ISSUE THREAD

**Issue by ggicci** [ggicci/httpin#27]
Though **httpin** had provided an easy way to [add your custom directive](https://ggicci.github.io/httpin/directives/custom). If httpin can provide some common used directives, it would be helpful.

e.g.

- [ ] to_lower
- [ ] to_upper
- [x] default, by #26 
- add more here...

**Comment by SharkFourSix** [comment]
Also, consider adding a default implementation of "path" directive. It's because of lack of it that will force developers to include other libraries just for that one single functionality, which is not good because of bloatware from transitive packages.

**Comment by ggicci** [comment]
Hi @SharkFourSix, httpin does not support routing functionality, while the decoding of path variables relys on it. Please read https://ggicci.github.io/httpin/directives/path for more details.
