### ISSUE TITLE
replace default decoder for JSON

### ISSUE THREAD

**Issue by bokunodev** [ggicci/httpin#37]
i've been using [json-iterator/go](https://github.com/json-iterator/go) for a long time, having ability to replace default decoder for json would be great.
or better, being able to add custom request body format like bson,msgpack,cbor etc.

**Comment by ggicci** [comment]
Sounds great, I will have some investigations on this.

**Comment by bokunodev** [comment]
we could make this preferences globally and i'd just works for me.
we just need to add a function `RegisterBodyDecoder(string, SomeInterface )`
or make it configurable trough [httpin.Option](https://pkg.go.dev/github.com/ggicci/httpin#Option)

**Comment by ggicci** [comment]
I hope [v0.9.0](../releases/v0.9.0) is what you need.

Documentation: https://ggicci.github.io/httpin/directives/body#custom-body-decoders

**Comment by ggicci** [comment]
Closed and feel free to reopen it. Any suggestions are welcome :)
