### ISSUE TITLE
How do I use httpin.RegisterTypeDecoder in the latest version?

### ISSUE THREAD

**Issue by vamshiaruru32** [ggicci/httpin#69]
Hello everyone, I am currently on httpin 0.11.0 and I use `httpin.RegisterTypeDecoder` to register types for pointer fields (I do not want to use the new patch fields because of personal preferences). But looks like the method has been removed in 0.12.0 as part of refactor. What is the new way of registering a new type decoder? 

Previous code:
```go
func decodeStringPointer(value string) (any, error) {
	return &value, nil
}

func init() {
	strVal := "some string"
	httpin.RegisterTypeDecoder(reflect.TypeOf(&strVal), httpin.ValueTypeDecoderFunc(decodeStringPointer))
}
```

What's the new code?
Thanks in advance!

**Comment by ggicci** [comment]
Hi @vamshiaruru32, sorry the new code brought in some breacking changes of the APIs.

Quick answer here:

```go
func decodeStringPointer(value string) (any, error) {
	return &value, nil
}

func init() {
	httpin.RegisterValueTypeDecoder[*string](httpin.DecoderFunc[string](decodeStringPointer))
}
```

But for the latest version [v0.14.0](https://github.com/ggicci/httpin/releases/tag/v0.14.0), you don't need to create pointer type decoders, it's already been registered automatically by httpin.

**Comment by vamshiaruru32** [comment]
Thank you! I have upgraded to 0.14.0 and removed the register functions, and everything is working. I'll be closing this issue now :)

**Comment by CleverCoder** [comment]
This should mandate a MAJOR version number change per semver. 😢
